## Tasks

### Task 1 Task 1: Source the Data Set


Datasets

In [1]:
# Import datasets

import pandas as pd
import sklearn as skl
import numpy as np


* Resources
    - https://archive.ics.uci.edu/datasets
    - https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html




* Loading Datasets
    - https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html


In [ ]:
# load the dataset.
data = skl.datasets.load_iris()


* what does the load_iris() function returns?

    It's a sort of a dictionnary that shows all the dataset information. It lists the Data istelf and other grouped information linked to it.

### Task 2: Explore the Data Structure


* Resources:
    - https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html#sklearn.datasets.load_iris
    - https://scikit-learn.org/1.4/auto_examples/datasets/plot_iris_dataset.html

Printing and explaining the shape of the data set, the first and last 5 rows of the data, the feature names, and the target classes.

* The shape of dataset      : the dataframe shows a table of 3 classes, 4 columns with 150 lines. The data frame represents Three iris species with 50 samples each.
* The first 5 rows of data  : **Setosa** features *sepal length (cm)', 'sepal width (cm)', 'petal length (cm)','petal width (cm)'*
* The last 5 rows of data   : **virginica** features *sepal length (cm)', 'sepal width (cm)', 'petal length (cm)','petal width (cm)'*
* The features names        : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
* The target classes        : 'setosa', 'versicolor', 'virginica'

In [2]:
# load the dataset as a pandas dataframe.
from sklearn.datasets import load_iris
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names,)


df['species'] = pd.Categorical.from_codes(data.target, data.target_names)
# Categorical data is a Pandas data type representing particular (fixed) numbers of class or distinct values.
# list(data.target_names)
# display(df)

In [ ]:
data['data'].shape

(150, 4)

In [ ]:
# Return values of data
# it's lik a dictionary with keys and values
data = load_iris()

In [ ]:
# Return the keys of the data
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
# description of the dataset and the features
data['data']


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
# data['target'] is the target variable
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

### Task 3: Summarize the Data


calculating and displaying the following values for each feature in the dataset:

* mean
* minimum
* maximum
* standard deviation
* median

In [ ]:
data['feature_names']


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [3]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [ ]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [4]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica

In [5]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [12]:
df['sepal length (cm)'].value_counts().mean()
df['sepal length (cm)'].value_counts().min()
df['sepal length (cm)'].value_counts().max()
df['sepal length (cm)'].value_counts().std()
df['sepal length (cm)'].value_counts().median()

np.float64(4.0)

In [13]:
df['sepal width (cm)'].value_counts().mean()
df['sepal width (cm)'].value_counts().min()
df['sepal width (cm)'].value_counts().max()
df['sepal width (cm)'].value_counts().std()
df['sepal width (cm)'].value_counts().median()

np.float64(5.0)

In [14]:
df['petal length (cm)'].value_counts().mean()
df['petal length (cm)'].value_counts().min()
df['petal length (cm)'].value_counts().max()
df['petal length (cm)'].value_counts().std()
df['petal length (cm)'].value_counts().median()

np.float64(3.0)

In [15]:
df['petal width (cm)'].value_counts().mean()
df['petal width (cm)'].value_counts().min()
df['petal width (cm)'].value_counts().max()
df['petal width (cm)'].value_counts().std()
df['petal width (cm)'].value_counts().median()

np.float64(5.5)

In [16]:
df['sepal length (cm)'].mean

<bound method Series.mean of 0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: float64>

In [51]:
df[:5]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [85]:
x[145:150]

array([[6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [83]:
x[145:len(x)]

array([[6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [84]:
x[145:]

array([[6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [70]:
x = np.array(data['data'])

In [38]:
x[:,0].mean()


np.float64(5.843333333333334)

In [17]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64